import Head from 'next/head'
import Layout from '../components/Layout'
import Home from '../components/Home'
import About from '../components/About'
import Works from '../components/Works'
import Testimonial from '../components/Testimonial'

export default function Homepage() {
  return (
    <>
      <Head>
        <title>Konuşarak Öğren | Frontend Case</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Home />
        <About />
        <Works />
        <Testimonial />
      </Layout>
    </>
      
  )
}
